const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt1",
      category: "Shirts",
      image: "/images/1.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "2",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt2",
      category: "Shirts",
      image: "/images/2.png",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "3",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt3",
      category: "Shirts",
      image: "/images/3.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "4",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt4",
      category: "Shirts",
      image: "/images/4.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};

export default data;
